package com.franciscogarciagarzon.learningpath.ui.theme

import androidx.compose.ui.graphics.Color

//val Purple80 = Color(0xFFD0BCFF)
//val PurpleGrey80 = Color(0xFFCCC2DC)
//val Pink80 = Color(0xFFEFB8C8)
val PokeRed = Color(0xFFFF1C1C)

//val Purple40 = Color(0xFF6650a4)
//val PurpleGrey40 = Color(0xFF625b71)
//val Pink40 = Color(0xFF7D5260)
val LightBlue = Color(0xFFBAC7FF)
val lightGrey = Color(0xFFAAAAAA)

val HPColor = Color(0xFFF5FF00)
val AtkColor = Color(1f, 0f, 0f, 0.66f)
val DefColor = Color(0f, 0f, 1f, 0.44f)
val SpAtkColor = Color(0.671f, 0f, 1f, 0.57f)
val SpDefColor = Color(1f, 0f, 0.8f, 0.7f)
val SpdColor = Color(0f, 1f, 0.063f, 0.55f)


val ColorBug = Color(0xFF94bc4a)
val ColorDark = Color(0xFF736c75)
val ColorDragon = Color(0xFF6a7baf)
val ColorElectric = Color(0xFFe5c531)
val ColorFairy = Color(0xFFe397d1)
val ColorFighting = Color(0xFFcb5f48)
val ColorFire = Color(0xFFea7a3c)
val ColorFlying = Color(0xFF7da6de)
val ColorGhost = Color(0xFF846ab6)
val ColorGrass = Color(0xFF71c558)
val ColorGround = Color(0xFFcc9f4f)
val ColorIce = Color(0xFF70cbd4)
val ColorNormal = Color(0xFFaab09f)
val ColorPoison = Color(0xFFb468b7)
val ColorPsychic = Color(0xFFe5709b)
val ColorRock = Color(0xFFb2a061)
val ColorSteel = Color(0xFF89a1b0)
val ColorWater = Color(0xFF539ae2)


val md_theme_light_primary = Color(0xFF745B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE08D)
val md_theme_light_onPrimaryContainer = Color(0xFF241A00)
val md_theme_light_secondary = Color(0xFF105FAA)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001C3A)
val md_theme_light_tertiary = Color(0xFF215FA6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD5E3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001C3B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFEBE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF7E7667)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFF2C000)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF745B00)
val md_theme_light_outlineVariant = Color(0xFFCFC5B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF2C000)
val md_theme_dark_onPrimary = Color(0xFF3D2F00)
val md_theme_dark_primaryContainer = Color(0xFF584400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE08D)
val md_theme_dark_secondary = Color(0xFFA5C8FF)
val md_theme_dark_onSecondary = Color(0xFF00315E)
val md_theme_dark_secondaryContainer = Color(0xFF004785)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_tertiary = Color(0xFFA6C8FF)
val md_theme_dark_onTertiary = Color(0xFF00315F)
val md_theme_dark_tertiaryContainer = Color(0xFF004787)
val md_theme_dark_onTertiaryContainer = Color(0xFFD5E3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC5B4)
val md_theme_dark_outline = Color(0xFF989080)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF745B00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF2C000)
val md_theme_dark_outlineVariant = Color(0xFF4C4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFCB05)